import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideAnimations } from '@angular/platform-browser/animations';
import {
  LucideAngularModule,
  Menu,
  PanelLeft,
  Search,
  Bell,
  ChevronDown,
  User,
  LogOut,
  ShoppingBag,
  Store,
  LayoutDashboard,
  Upload,
  FileText,
  Users,
  ShieldCheck,
  ClipboardList,
  Settings,
  Check,
  SlidersHorizontal,
  Wallet,
  Lock,
  Zap,
  BookOpen,
  GraduationCap,
  Award,
  Clock,
  BadgeCheck,
  TrendingUp,
  Star,
  ArrowRight,
  Instagram,
  Twitter,
  Linkedin,
  Youtube,
  LayoutTemplate,
  Plus,
  Trash2,
  GripVertical,
  Image,
  Highlighter,
} from 'lucide-angular';
import { routes } from './app.routes';
import { authInterceptor } from '@core/interceptors/auth.interceptor';
import { errorInterceptor } from '@core/interceptors/error.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor, errorInterceptor])),
    provideAnimations(),
    importProvidersFrom(
      LucideAngularModule.pick({
        Menu,
        PanelLeft,
        Search,
        Bell,
        ChevronDown,
        User,
        LogOut,
        ShoppingBag,
        Store,
        LayoutDashboard,
        Upload,
        FileText,
        Users,
        ShieldCheck,
        ClipboardList,
        Settings,
        Check,
        SlidersHorizontal,
        Wallet,
        Lock,
        Zap,
        BookOpen,
        GraduationCap,
        Award,
        Clock,
        BadgeCheck,
        TrendingUp,
        Star,
        ArrowRight,
        Instagram,
        Twitter,
        Linkedin,
        Youtube,
        LayoutTemplate,
        Plus,
        Trash2,
        GripVertical,
        Image,
        Highlighter,
      }),
    ),
  ],
};
