-- ============================================================
--  TopNotes — PRODUCTION (Render PostgreSQL) migration
--  Phase 2: consent infrastructure
--
--  NOTE: local dev runs on MySQL, PRODUCTION runs on PostgreSQL
--  (Render), so this script is PostgreSQL syntax.
--
--  Adds:
--    • agreement_documents  (versioned legal text + content hash)
--    • consent_records      (append-only acceptance audit trail)
--
--  Run ONCE:
--    psql "postgresql://USER:PASS@HOST/DB?sslmode=require" -f docs/PROD_DB_MIGRATION_CONSENT.sql
--
--  Idempotent (IF NOT EXISTS everywhere). AFTER running, RESTART the backend so
--  AgreementSeeder seeds v1 of the Seller Agreement & Originality Declaration.
-- ============================================================

BEGIN;

-- ── 1. Versioned agreement text ─────────────────────────────
CREATE TABLE IF NOT EXISTS agreement_documents (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type         VARCHAR(40)  NOT NULL,
  version      INTEGER      NOT NULL,
  title        VARCHAR(200) NOT NULL,
  body         TEXT         NOT NULL,
  content_hash VARCHAR(64)  NOT NULL,
  active       BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMP(6) NOT NULL,
  CONSTRAINT uk_agreement_type_version UNIQUE (type, version)
);

-- ── 2. Append-only consent audit trail ──────────────────────
CREATE TABLE IF NOT EXISTS consent_records (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT      NOT NULL REFERENCES users(id),
  agreement_type VARCHAR(40) NOT NULL,
  version        INTEGER     NOT NULL,
  content_hash   VARCHAR(64) NOT NULL,
  note_id        BIGINT,
  ip_address     VARCHAR(45),
  user_agent     VARCHAR(512),
  accepted_at    TIMESTAMP(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_consent_user_type ON consent_records(user_id, agreement_type);
CREATE INDEX IF NOT EXISTS idx_consent_note ON consent_records(note_id);

COMMIT;
