-- ============================================================
--  TopNotes — PRODUCTION (Render PostgreSQL) schema migration
--
--  NOTE: local dev runs on MySQL, but PRODUCTION runs on
--  PostgreSQL (Render), so this script is PostgreSQL syntax.
--
--  Adds everything introduced by:
--    • per-category seller qualification
--    • admin taxonomy (Category → Exam → Subject)
--    • landing CMS + platform config
--    • taxonomy denormalisation on notes
--
--  Run ONCE:
--    psql "postgresql://USER:PASS@HOST/DB?sslmode=require" -f docs/PROD_DB_MIGRATION.sql
--
--  Fully idempotent (IF NOT EXISTS everywhere, FKs guarded) — safe to re-run.
--  AFTER running, RESTART the backend so the seeders populate taxonomy /
--  platform_config / grandfather qualifications; site_content seeds on the
--  first GET /content/landing.
-- ============================================================

BEGIN;

-- ── 1. Taxonomy ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS exam_categories (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INTEGER NOT NULL DEFAULT 0,
  name          VARCHAR(100) NOT NULL,
  CONSTRAINT uk_exam_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS exams (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INTEGER NOT NULL DEFAULT 0,
  name          VARCHAR(120) NOT NULL,
  category_id   BIGINT NOT NULL REFERENCES exam_categories(id),
  CONSTRAINT uk_exam_cat_name UNIQUE (category_id, name)
);

CREATE TABLE IF NOT EXISTS subjects (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INTEGER NOT NULL DEFAULT 0,
  name          VARCHAR(120) NOT NULL,
  exam_id       BIGINT NOT NULL REFERENCES exams(id),
  CONSTRAINT uk_subject_exam_name UNIQUE (exam_id, name)
);

-- ── 2. Per-category seller qualification ────────────────────
CREATE TABLE IF NOT EXISTS seller_qualifications (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  approved_at      TIMESTAMP(6),
  attempts_used    INTEGER NOT NULL DEFAULT 0,
  best_score       INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMP(6) NOT NULL,
  last_attempt_at  TIMESTAMP(6),
  marksheet_url    TEXT,
  rejection_reason TEXT,
  status           VARCHAR(24) NOT NULL,
  updated_at       TIMESTAMP(6) NOT NULL,
  category_id      BIGINT NOT NULL REFERENCES exam_categories(id),
  seller_id        BIGINT NOT NULL REFERENCES users(id),
  CONSTRAINT uk_sq_seller_category UNIQUE (seller_id, category_id)
);
CREATE INDEX IF NOT EXISTS idx_sq_seller ON seller_qualifications(seller_id);
CREATE INDEX IF NOT EXISTS idx_sq_status ON seller_qualifications(status);

-- ── 3. Landing CMS + platform config ────────────────────────
CREATE TABLE IF NOT EXISTS site_content (
  page_key   VARCHAR(50) PRIMARY KEY,
  content    TEXT,
  updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS platform_config (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_key   VARCHAR(100) NOT NULL,
  config_value TEXT NOT NULL,
  description  VARCHAR(350),
  updated_at   TIMESTAMP(6),
  CONSTRAINT uk_config_key UNIQUE (config_key)
);

-- ── 4. New columns on existing tables (idempotent) ──────────
ALTER TABLE notes ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE notes ADD COLUMN IF NOT EXISTS exam     VARCHAR(120);
ALTER TABLE notes ADD COLUMN IF NOT EXISTS subject  VARCHAR(100);

ALTER TABLE test_config        ADD COLUMN IF NOT EXISTS category_id BIGINT;
ALTER TABLE test_questions     ADD COLUMN IF NOT EXISTS category_id BIGINT;
ALTER TABLE verification_tests ADD COLUMN IF NOT EXISTS category_id BIGINT;

-- ── 5. FKs for the new category_id columns (skip if present) ─
DO $$ BEGIN
  ALTER TABLE test_config ADD CONSTRAINT fk_testconfig_category
    FOREIGN KEY (category_id) REFERENCES exam_categories(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE test_questions ADD CONSTRAINT fk_testq_category
    FOREIGN KEY (category_id) REFERENCES exam_categories(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE verification_tests ADD CONSTRAINT fk_verif_category
    FOREIGN KEY (category_id) REFERENCES exam_categories(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

COMMIT;
