-- ============================================================
--  TopNotes — PRODUCTION (Render PostgreSQL) migration
--  Phase 1: email verification + optional phone
--
--  NOTE: local dev runs on MySQL, PRODUCTION runs on PostgreSQL
--  (Render), so this script is PostgreSQL syntax.
--
--  Adds:
--    • users.email_verified  (OTP email confirmation flag)
--    • users.phone made nullable (optional for buyers)
--    • email_verification_tokens  (single-use, hashed OTP codes)
--
--  Run ONCE:
--    psql "postgresql://USER:PASS@HOST/DB?sslmode=require" -f docs/PROD_DB_MIGRATION_AUTH.sql
--
--  Fully idempotent (IF NOT EXISTS / DROP NOT NULL no-ops) — safe to re-run.
-- ============================================================

BEGIN;

-- ── 1. users.email_verified ─────────────────────────────────
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;

-- Grandfather every EXISTING account as verified so the new seller-test gate
-- and buyer nudge don't disrupt current users. New signups insert FALSE.
UPDATE users SET email_verified = TRUE WHERE email_verified = FALSE;

-- ── 2. Phone optional (buyers may omit it) ──────────────────
ALTER TABLE users ALTER COLUMN phone DROP NOT NULL;

-- ── 3. Email verification OTP tokens ────────────────────────
CREATE TABLE IF NOT EXISTS email_verification_tokens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code_hash   VARCHAR(255) NOT NULL,
  expires_at  TIMESTAMP(6) NOT NULL,
  consumed_at TIMESTAMP(6),
  attempts    INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMP(6) NOT NULL,
  user_id     BIGINT NOT NULL REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_evt_user ON email_verification_tokens(user_id);

COMMIT;
